import SwiftUI

struct AboutView: View {
    var body: some View {
        Form {
            Section {
                HStack { Text("Version"); Spacer(); Text("1.0").foregroundColor(.secondary) }
                HStack { Text("AI Provider"); Spacer(); Text("Google Gemini").foregroundColor(.secondary) }
            }
            Section("About") {
                Text("AI Keyboard is a native-style iPhone keyboard with on-demand AI rewriting. Type normally, tap AI, swipe between three rewrite cards, pick a tone, and tap a rewrite to instantly replace your text.")
                    .font(.callout)
                    .foregroundColor(.secondary)
            }
            Section("How it works") {
                Text("Rewrites are generated by Google Gemini using the API key you provide. Typing is always instant — AI runs asynchronously and never blocks the keyboard.")
                    .font(.callout)
                    .foregroundColor(.secondary)
            }
        }
        .navigationTitle("About")
    }
}
