import SwiftUI
import UIKit

/// Settings screen: Gemini API key configuration (secure entry, show/hide, save,
/// test connection, status) plus the app's toggles.
struct SettingsView: View {
    var onChange: () -> Void = {}

    @StateObject private var model = GeminiSettingsModel()
    @State private var enableAI = SettingsStore.shared.enableAI
    @State private var autocorrect = SettingsStore.shared.autocorrect
    @State private var predictions = SettingsStore.shared.predictions
    @State private var theme = SettingsStore.shared.theme

    var body: some View {
        Form {
            Section {
                HStack {
                    Group {
                        if model.showKey {
                            TextField("Gemini API Key", text: $model.apiKey)
                        } else {
                            SecureField("Gemini API Key", text: $model.apiKey)
                        }
                    }
                    .textInputAutocapitalization(.never)
                    .disableAutocorrection(true)
                    .font(.system(.body, design: .monospaced))

                    Button(model.showKey ? "Hide" : "Show") { model.showKey.toggle() }
                        .font(.footnote)
                        .buttonStyle(.borderless)
                }

                Button("Save") {
                    model.save()
                    onChange()
                }

                Button("Copy Key to Clipboard") {
                    model.copyToClipboard()
                }
                .disabled(model.apiKey.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)

                Button {
                    Task { await model.test() }
                } label: {
                    HStack {
                        Text("Test Connection")
                        if model.testing {
                            Spacer()
                            ProgressView()
                        }
                    }
                }
                .disabled(model.testing)

                HStack {
                    Text("Status")
                    Spacer()
                    Text(model.status.text).foregroundColor(model.status.color)
                }
            } header: {
                Text("Gemini API")
            } footer: {
                Text("Get a free key at ai.google.dev. Save the key here, tap Copy Key to Clipboard, then in the keyboard tap AI and Paste API Key once. The key is stored in the Keychain on this device and only sent to Google when rewriting.")
            }

            Section("AI") {
                Toggle("Enable AI", isOn: $enableAI)
                    .onChange(of: enableAI) { newValue in SettingsStore.shared.enableAI = newValue }
                HStack {
                    Text("AI Provider")
                    Spacer()
                    Text("Gemini").foregroundColor(.secondary)
                }
            }

            Section("Typing") {
                Toggle("Autocorrect", isOn: $autocorrect)
                    .onChange(of: autocorrect) { newValue in SettingsStore.shared.autocorrect = newValue }
                Toggle("Predictions", isOn: $predictions)
                    .onChange(of: predictions) { newValue in SettingsStore.shared.predictions = newValue }
            }

            Section("Appearance") {
                Picker("Theme", selection: $theme) {
                    Text("System").tag("system")
                    Text("Light").tag("light")
                    Text("Dark").tag("dark")
                }
                .onChange(of: theme) { newValue in SettingsStore.shared.theme = newValue }
            }

            Section("Languages") {
                HStack {
                    Text("Keyboard Language")
                    Spacer()
                    Text("English").foregroundColor(.secondary)
                }
            }

            Section {
                Text("Rewrites are generated by Google Gemini using your API key. Text you send for rewriting is transmitted to Google. This app stores nothing beyond your settings and key.")
                    .font(.footnote)
                    .foregroundColor(.secondary)
            } header: {
                Text("Privacy")
            }

            Section("Future Model Management") {
                Text("On-device models can be added here later. AI already runs through a provider abstraction, so a local provider can be dropped in without changing the keyboard.")
                    .font(.footnote)
                    .foregroundColor(.secondary)
            }
        }
        .navigationTitle("Settings")
    }
}

/// View model for the Gemini configuration section.
final class GeminiSettingsModel: ObservableObject {
    @Published var apiKey: String = ""
    @Published var showKey = false
    @Published var testing = false
    @Published var status: Status = .unknown

    enum Status: Equatable {
        case unknown, connected(String), missing, invalid, error(String)

        var text: String {
            switch self {
            case .unknown:              return "Not tested"
            case .connected(let m):     return m.isEmpty ? "Gemini Connected" : "Gemini Connected (\(m))"
            case .missing:              return "API Key Missing"
            case .invalid:              return "Invalid API Key"
            case .error(let m):         return m
            }
        }
        var color: Color {
            switch self {
            case .connected:            return .green
            case .missing, .invalid:    return .orange
            case .error:                return .red
            case .unknown:              return .secondary
            }
        }
    }

    init() {
        apiKey = SecretStore.shared.apiKey() ?? ""
        status = apiKey.isEmpty ? .missing : .unknown
    }

    func copyToClipboard() {
        let trimmed = apiKey.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        UIPasteboard.general.string = trimmed
    }

    func save() {
        let trimmed = apiKey.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { status = .missing; return }
        SecretStore.shared.saveAPIKey(trimmed)
        apiKey = trimmed
        status = .unknown
    }

    @MainActor
    func test() async {
        let trimmed = apiKey.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { status = .missing; return }
        SecretStore.shared.saveAPIKey(trimmed)   // persist latest before testing
        guard let provider = AIProviderFactory.makeProvider() else { status = .missing; return }

        testing = true
        defer { testing = false }
        do {
            let model = try await provider.testConnection()
            status = .connected(model)
        } catch let error as AIError {
            if case .invalidKey = error {
                status = .invalid
            } else {
                status = .error(error.errorDescription ?? "Connection failed")
            }
        } catch {
            status = .error(error.localizedDescription)
        }
    }
}
